CREATE DATABASE IF NOT EXISTS administracao;

CREATE TABLE IF NOT EXISTS administracao.cliente ( 
id int NOT NULL AUTO_INCREMENT,
PRIMARY KEY (id), 
nome VARCHAR(150) NOT NULL, 
data_nascimento DATE NOT NULL,
cpf VARCHAR(11) NOT NULL, 
rg VARCHAR(20) NOT NULL,
telefone VARCHAR(10) NOT NULL) 
CHARSET=utf8 COLLATE utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS administracao.usuario (
id int NOT NULL AUTO_INCREMENT,
PRIMARY KEY (id), 
login VARCHAR(150) NOT NULL, 
senha VARCHAR(150) NOT NULL) 
CHARSET=utf8 COLLATE utf8_unicode_ci;